appId: "bestrong-api"

activeColor: blue

service:
  port: 80

ingress:
  host: bestrong.pp.ua
  tls:
    secretName: bestrong-tls

persistence:
  size: 5Gi
  hostPath:
    path: /mnt/bestrong-sqlite
