apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bestrong.fullname" . }}
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bestrong.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bestrong.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: sqlite-storage
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ include "bestrong.fullname" . }}-pvc
      {{- end }}
