apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-stable
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-preview
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bestrong.fullname" . }}
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
