grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.bestrong.pp.ua
    ingressClassName: traefik
    tls:
    - hosts:
      - grafana.bestrong.pp.ua
      secretName: bestrong-wildcard-tls
      
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: default-cluster